services:
  db:
    image: postgres
    container_name: db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
    - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
    ports:
      - 6400:6400
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  db-data:
